### ISSUE TITLE
안내 문서 작성에 관하여

### ISSUE THREAD

**Issue by ChangJoo-Park** [partnerlabs/grap-ui-framework#7]
현재 방법이 생각보다 문서 작성하는데 불편한 점이 많은 것 같습니다.
어떻게 해야 문서 만들기 편할지 고민해봐야할 것 같습니다.

**Comment by devjin0617** [comment]
넵 맞아요. 뭔가 형식을 맞춰서 추가해놓으면 양식에 맞춰서 자동으로 문서가 작성 될 수 있도록 해야할텐데..... (고민만..)

**Comment by ChangJoo-Park** [comment]
고민만하다가 수동으로 하고 있어요 아직 만들어야 할게 많으니까 다 만들고 나서 예제 뽑으면서 해도 뭐...
되겠죠 ㅋㅋ

**Comment by devjin0617** [comment]
@ChangJoo-Park 감사합니다 : )

**Comment by ChangJoo-Park** [comment]
ㅋㅋ 휴간데 업무하지 마세요

**Comment by devjin0617** [comment]
@ChangJoo-Park 이것까지는 업무와 취미생활 중간이라고 해두죠 ㅎ.ㅎ

**Comment by devjin0617** [comment]
깜짝놀랬네요
